### ISSUE TITLE
RStudio Server port not open

### ISSUE THREAD

**Issue by adfi** [cloudyr/AzureVM#1]
Hi,  

Thanks for your work on the package and writing up all the instructions. I managed to succesfully create a DSVM and startup RStudio Server. However, I could not access RStudio at first. Upon closer inspection, I noticed the port needed by RStudio wasn't getting through the firewall. After updating the firewall rules I managed to connect to RStudio.

Is this something you need to update in the template?

**Comment by Hong-Revo** [comment]
The template is actually obtained from [Azure/DataScienceVM](https://github.com/Azure/DataScienceVM); I don't make any changes to it (other than formatting).

I'll make a suggestion that they should open the RStudio Server port on the Linux images.

**Comment by adfi** [comment]
Thanks, I'll keep an eye out on the new issue.
